server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: gamept-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: gamept
          application: gamept
          __path__: /var/log/gamept/*.log
    
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3}) \[(?P<thread>.*?)\] (?P<level>\w+)\s+(?P<logger>.*?) - (?P<message>.*)'
      - labels:
          level:
          thread:
          logger:
      - timestamp:
          source: timestamp
          format: '2006-01-02 15:04:05.000'
      - output:
          source: message
